---
AWSTemplateFormatVersion: 2010-09-09
Description: IEEEEEEEE
Resources:
  AnotherBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: tatch-sample-another-bucket
  FooBarBaz:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: tatch-foo-bar-baz
