# vi: set ft=ruby :

$script = <<-SCRIPT
sudo apt update
sudo apt upgrade -y
sudo apt-get install -y build-essential \
    zlib1g-dev \
    libssl-dev \
    libbz2-dev \
    libreadline-dev \
    libsqlite3-dev
git clone https://github.com/pyenv/pyenv.git ~/.pyenv
echo eval "$(pyenv init -)" >> ~/.bash
echo 'export PYENV_ROOT="$HOME/.pyenv"' >> ~/.bashrc
echo 'export PATH="$PYENV_ROOT/bin:$PATH"' >> ~/.bashrc
SCRIPT

Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/bionic64"
  config.vm.provision "shell", privileged: false, inline: $script
end
