# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/xenial64"
  config.vm.network "private_network", ip: "192.168.10.101"
  config.vm.provision "shell", privileged: false, inline: <<-SHELL
      set -i
      sudo apt-get update
      sudo apt-get -y install nginx build-essential libssl-dev libreadline-dev
      git clone https://github.com/rbenv/rbenv.git ~/.rbenv
      git clone https://github.com/rbenv/ruby-build.git ~/.rbenv/plugins/ruby-build
      echo 'export PATH="$HOME/.rbenv/bin:$PATH"' >> ~/.bashrc
      echo 'eval "$(rbenv init -)"' >> ~/.bashrc
      source ~/.bashrc
      rbenv install 2.4.0
      rbenv global 2.4.0
      gem install bundler
      git clone https://github.com/ItinoseSan/nginx-web-app-study.git
      mv nginx-web-app-study/ nginx-sinatra/
      cd nginx-sinatra/
      bundle install
      sudo ln -s /home/vagrant/nginx-sinatra/ /var/www/nginx-sinatra
      sudo cp config/nginx.conf /etc/nginx/nginx.conf
      mkdir -p var/{run,log}
  SHELL
end
