# vi: set ft=ruby :
Vagrant.configure("2") do |config|
  config.vm.box = "centos/7"
  config.vm.network "private_network", ip: "192.168.100.20"
  config.vm.provision "shell", path: "setup_remote_user.sh"
end
